name: memories_app
description: A realtime photo sharing app built on Supabase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.5.0
  go_router: ^6.5.0
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  file_picker: ^5.2.6
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  riverpod_generator: ^2.1.4
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
